title: HHU-ANN-2023
description: YOUR DESCRIPTION
theme: just-the-docs

url: https://0xc0de996.github.io/0xc0de996

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/0xc0de996/0xc0de996