title: HHU-ANN-2023
description: 河海大学人工智能学院2023年春季人工神经网络
theme: just-the-docs
remote_theme: pmarsceill/just-the-docs

url: https://0xc0de996.github.io

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/YOUR-USERNAME/YOUR-SITE-NAME